[package]
name = "nightcycle/boat-graph"
description = "Modified port of BoatBomber's Graph Module to Wally"
version = "1.0.0"
authors = ["CJ Oyer <coyer@nightcycle.us>", "boatbomber <zack@boatbomber.com>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
maid = "quenty/maid@^2.0.1-canary"
